### ISSUE TITLE
Multiple days on a recurring week

### ISSUE THREAD

**Issue by leonardo2204** [bakineggs/recurring_events_for#4]
Hi @bakineggs!

Thanks for this great repo, it is really helpful!
I'm trying to figure out how can I have multiple days on a weekly recurring event, do I need to create multiple event_recurrence rows for each day?

For instance, if I create an event that happens every Monday and Tuesday every week, I'll end up with two event_recurrences entries, is that correct? Would it make sense to create an array for the "days" column?

Thanks again!

**Comment by bakineggs** [comment]
Yea, you can create a weekly recurring event that happens on multiple days of the week by creating two event_recurrences entries. One of the specs covers that scenario: https://github.com/bakineggs/recurring_events_for/blob/2c38eff/spec/recurring_events_for_spec.rb#L593

It would make sense to switch from a day column to a days array column. The week column could also switch to a weeks array and month to a months array. If all three of those were arrays, then the event_recurrences table would need a maximum of 1 row per event_id, so the event_recurrences table wouldn't be needed at all: the days, weeks, and months array columns could be moved to the events table. Same thing with the event_cancellations table: it could be replaced with a dates array column on the events table. Then all the information about an event and its schedule could be in the events table instead of spread across 3 tables, which could make it a bit easier to use. It's a good idea, but I'm not going to devote the time to do it. If you want to take a crack at it, feel free!

Thanks!

**Comment by leonardo2204** [comment]
Thanks for replying, I'll close the issue and give it a try!
If I can come up with a solution, I'll open a PR.

Thanks again for the help!
