### ISSUE TITLE
Map metadata

### ISSUE THREAD

**Issue by leonardo2204** [bakineggs/recurring_events_for#5]
I have one more [philosophiocal] doubt in your code.
Let's suppose that the code should contain an attendees table (like Google Calendar), along with metadata. How should I map this table?

The first thing that came to my mind is creating a new table that contains the eventId + startDate, but I'm not sure if I'd be breaking the "do not materialize each event" rule here. Is there a better solution?

Thanks!

**Comment by bakineggs** [comment]
You can use eventId + startDate to map associated data like attendees. That's what we did at the company where I worked when I created this repo. We had scheduled jobs that would materialize events as they happened so that users could change the repetition rules for upcoming events without affecting past events. We used this function to see what dates an event would occur in the future and had rows for each time the event had happened in the past. Things get a little tricky when you use eventId + startDate for data associated with future events and the user changes the repetition rules so that the startDate changes: you have to decide which data to automatically move over to which other startDates, which data the user has to re-enter or verify, etc.

**Comment by leonardo2204** [comment]
Hey, sorry for the delayed reply, I hope you had a good holiday!
That's quite what I thought, I'm only struggling to choose which date would fit better this use case, either the starts_on or starts_at, since they are mutually exclusive. Do you have any thoughts?

Thanks again for all the help, really appreciate it!
